[tool.poetry]
name = "csv-enricher"
version = "0.1.0"
description = ""
authors = ["recepsirin"]
readme = "README.md"
packages = [{include = "csv_enricher"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
